MOCK_DEFAULT_THEMES = [
    {
        "title": "表面張力の研究と実用性の検証",
        "description": "水の表面張力の性質を調べ、日常生活での応用例を探る物理実験です。",
        "genre": "experiment",
        "materials": ["水", "コップ", "クリップ", "洗剤", "コイン", "針"],
        "steps": [
            "表面張力の基本実験",
            "様々な液体での比較",
            "温度による変化を測定",
            "実用例の調査",
            "結果の考察",
        ],
        "estimated_days": 5,
        "difficulty": "medium",
    },
    {
        "title": "家族史から見る地域社会の変遷",
        "description": "家族の歴史を通して地域社会の変化を調べ、社会史的な視点で分析します。",
        "genre": "research",
        "materials": ["ノート", "録音機器", "カメラ", "古い写真", "地図"],
        "steps": [
            "家族へのインタビュー",
            "写真・資料の収集",
            "年表の作成",
            "地域史との比較",
            "社会変化の分析",
        ],
        "estimated_days": 14,
        "difficulty": "medium",
    },
    {
        "title": "気候変動が生物に与える影響の長期観察",
        "description": "季節の変化と生物の行動や形態変化の関係を長期間観察し、気候変動の影響を考察します。",
        "genre": "observation",
        "materials": ["カメラ", "温度計", "湿度計", "記録ノート", "定規"],
        "steps": [
            "観察地点の設定",
            "定期的な観察と記録",
            "気象データの収集",
            "データの分析",
            "気候変動との関連を考察",
        ],
        "estimated_days": 35,
        "difficulty": "hard",
    },
]
