MOCK_ACTIVE_PROJECTS = [
    {
        "id": "project-1",
        "user_id": "user-1",
        "theme_id": "theme-1",
        "title": "植物の成長観察",
        "description": "豆の成長を毎日記録する実験",
        "genre": "observation",
        "status": "in_progress",
        "start_date": "2025-07-01",
        "target_end_date": "2025-07-21",
        "custom_materials": [],
        "custom_steps": [],
        "progress_percentage": 65,
        "created_at": "2025-07-01",
        "updated_at": "2025-07-04",
    }
]

MOCK_PAST_PROJECTS = [
    {
        "id": "past-project-1",
        "user_id": "user-1",
        "theme_id": "theme-past-1",
        "title": "水の表面張力実験",
        "description": "水の表面張力について調べる実験",
        "genre": "experiment",
        "status": "completed",
        "start_date": "2024-08-01",
        "target_end_date": "2024-08-15",
        "actual_end_date": "2024-08-14",
        "custom_materials": ["水", "コップ", "クリップ"],
        "custom_steps": [],
        "progress_percentage": 100,
        "created_at": "2024-08-01",
        "updated_at": "2024-08-14",
    },
    {
        "id": "past-project-2",
        "user_id": "user-1",
        "theme_id": "theme-past-2",
        "title": "植物の光合成実験",
        "description": "光の強さと植物の成長の関係を調べる",
        "genre": "experiment",
        "status": "completed",
        "start_date": "2024-07-15",
        "target_end_date": "2024-08-05",
        "actual_end_date": "2024-08-03",
        "custom_materials": ["豆", "植木鉢", "LEDライト"],
        "custom_steps": [],
        "progress_percentage": 100,
        "created_at": "2024-07-15",
        "updated_at": "2024-08-03",
    },
]
